theme: jekyll-theme-cayman
title: Vector Anti-Cheat
description: Simple, elegant, beautiful Anti-Cheat for Minecraft.
show_downloads: true
vector:
  vector_repo_url: https://github.com/vector-anti-cheat/Vector/
  vector_download: https://github.com/downloadsomwhere.jar
  maintainer: https://github.com/ItsSyfe/
  maintainer_name: Syfe
