theme: jekyll-theme-cayman
vector:
  vector_repo_url: https://github.com/vector-anti-cheat/Vector/
  vector_download: https://github.com/downloadsomwhere.jar
  maintainer: https://github.com/ItsSyfe/
  maintainer_name: Syfe
